# Generated by Django 5.0.7 on 2024-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=50)),
                ('heroien', models.CharField(max_length=50)),
                ('releasedate', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
